/**
 * YAHIA — the runner. Emitted at the game's current SCALE.
 *
 * Authored at the game's own resolution rather than downscaled from reference
 * art. Design taken from the TUNISIA_HERO reference — dark curly hair, cream
 * tee, pink shorts, navy sneakers.
 *
 * Generated by a small rasterizer (see the rig script): limbs are tapered
 * capsules, the head is two ellipses, and two automatic passes do the work that
 * hand-drawn ASCII could not — an OUTLINE on every silhouette edge, and SHADING
 * that lights the top of each region while shadowing its underside and right
 * flank. Flat fills with no outline were the single biggest gap against the
 * reference art; anatomy was the second, so the head is now roughly a sixth of
 * body height instead of a third.
 *
 * Drawn in **right-facing profile**, not front-on. An auto-runner only ever
 * travels one direction, and a front-facing figure with legs splayed sideways
 * reads as a star jump however you animate it. Profile also gives the run cycle
 * somewhere to put a stride.
 *
 * Two frames the reference sheet doesn't have, because YAHIA needs them:
 *   SLIDE  — the second of the game's two verbs
 *   CORPSE — lying flat, because a body is a platform
 *
 * Legend:
 *   .  transparent   H  hair      S  skin      L  skin highlight
 *   s  skin shadow   T  shirt     t  shirt shadow
 *   P  shorts        p  shorts shadow
 *   B  shoe          b  shoe sole  K  eye
 */

import { px } from '../game/scale';

export const SPRITE_PALETTE: Record<string, string> = {
  K: '#17101a', // outline — every silhouette edge, which the flat version lacked
  H: '#241610', // hair
  h: '#3a2416',
  G: '#5c3a22', // curl highlights
  d: '#6d4026', // skin
  S: '#9c6038',
  L: '#c08050',
  D: '#4e2d1b', // far-side limbs, darkened so depth reads
  v: '#b8b0a0', // shirt
  T: '#e8e2d2',
  W: '#f8f5ec',
  q: '#cf7288', // shorts
  P: '#f0a0b0',
  Q: '#ffc2ce',
  n: '#232b3d', // shoes
  B: '#38455e',
  b: '#56658a',
  N: '#1a2030', // far-side shoe
};

export interface Sprite {
  readonly rows: readonly string[];
  /** Sprite pixels left of the hitbox's left edge. */
  readonly ox: number;
  /** Sprite pixels above the hitbox's top edge. */
  readonly oy: number;
}

/** Contact: near leg reaching forward and planted, far leg pushed off with the heel up. */
const RUN_1: readonly string[] = [
  '...........................KKKKKKKK.........................',
  '.........................KKhGhhhhhhKK.......................',
  '........................KhhHHHHHHhGhhK......................',
  '.......................KhHHhHGHHHHHHhK......................',
  '.......................KGHHHHHhHHHHGHHK.....................',
  '......................KHhHHHHHGHHhHHHHLK....................',
  '......................KHHGHhHHHHHHHKKKSLK...................',
  '......................KHHHHHHHhGHHHHLLSdK...................',
  '......................KHhHGHHHHHHhLLLKKdK...................',
  '.......................KHHHhHLLLLLLLSKSdK...................',
  '.......................KHHHGHLLLLLSSSSSdK...................',
  '........................KHHHHhdSSSSSSSdK....................',
  '.........................KHhGhddSSSSdddK....................',
  '..........................KHHHhSSSSSdddK....................',
  '.........................KWWHGhhSSSSddWK....................',
  '.........................KWWWWLSSSddWWWvK...................',
  '........................KTTTWWLLddddWWTvK...................',
  '........................KTTTvvSdddWWTTTTvK..................',
  '.......................KTTTTvvddWWWWTTTTvK..KKKK............',
  '.......................KTTTvvLdWWWTTTTTTvK..KLLLK...........',
  '.......................KTTTvvLdWTTTTTTTTvK..KSSdK...........',
  '.......................KTTTTvWdTTTTTTTTTvK.KSSdK............',
  '.......................KTTTTvWdTTTTTTTTTTvKLSSdK............',
  '......................KTTTTTTTWTTTTTTTTTTTWWSSdK............',
  '.....................KWTTTTTTTWTTTTTTTTTTTvWSSdK............',
  '.....................KTTTTTTTTTTTTTTTTTTTTvvSSdK............',
  '....................KvvTTTTTTTTTTTTTTTTTTTvvSSdK............',
  '...................KddvTTTTTTTTTTTTTTTTTvvvLSdK.............',
  '...................KDddTTTTTTTTTTTTTTTTTKKKLddK.............',
  '...................KDDdTTTTTTTTTTTTTTTvK...KKKK.............',
  '...................KDDDTTTTTTTTTTTTTTTvK....................',
  '....................KDDTTTTTTTTTTTTTTTvK....................',
  '....................KDDTTTTTTTTTTTTTTTvK....................',
  '.....................KDTTTTTTTTTTTTTTTvK....................',
  '.....................KDTTTTTTTTTTTTTTvvK....................',
  '......................KvTTTTTTTTTTTTTvvK....................',
  '......................KvTTTTTTTTTTTTTvvK....................',
  '......................KQTTTTTTTTTTTTTvvK....................',
  '.......................KvTTTTTTTTTTTTvK.....................',
  '.......................KvvTTTTTTTTTTvvK.....................',
  '.......................KQvvTTTTTTTTvvvQK....................',
  '.......................KQQvvvvTTTvvvvQqK....................',
  '......................KPPQQvvvvvvvvQQQPqK...................',
  '.....................KQPPPQQQQvvvQQQQPPPQK..................',
  '.....................KPPPPPQQQQQQQQPPPPPqK..................',
  '....................KPPPPPPPPPQQQPPPPPPPPqK.................',
  '....................KPPPPPPPPPPPPPPPPPPPPqK.................',
  '...................KPPPPPPPPPPPPPPPPPPPPPPqK................',
  '...................KPPPPPPPPPPPPPPPPPPPPPPqK................',
  '..................KdqPPPPPPPPPqqPPPPPPPPPqqLK...............',
  '.................KddqqPPPPPPqqKKqqPPPPPPPqqLK...............',
  '................KdDDdqqqPPqqKK..KKqPPPPPqqLSdK..............',
  '...............KdDDDddqqqqKK......KqqqqqqqLSdK..............',
  '..............KdDDDDDdddKK.........KKKqqLLSSdK..............',
  '.............KdDDDDDDDdK..............KLLLSSdK..............',
  '............KdDDDDDDDDK................KSSSSSdK.............',
  '..........KKnnnDDDDDKK.................KSSSSSdK.............',
  '........KKnnnnnnDDDK...................KSSSSSdK.............',
  '......KKnnNNNNNnDKK.....................KSSSSdK.............',
  '....KKnnNNNNNNNNK.......................KSSdddK.............',
  '...KnnNNNNNNNNNK........................KdddddK.............',
  '...KNNNNNNNNNKK.........................KddbbdK.............',
  '...KNNNNNNNKK...........................KbbbbbK.............',
  '...KNNNNNKK..............................KbBBbbK............',
  '....KKKKK...............................KBBBBBBbKK..........',
  '........................................KBBBBBBBbbKK........',
  '.........................................KnBBBBBBBbbK.......',
  '.........................................KKnnBBBBBBBbK......',
  '...........................................KKnBBBBBBBbK.....',
  '.............................................KnnBBBBBnK.....',
  '..............................................KKnnnnnnK.....',
  '................................................KKKKKK......',
];

/** Passing: the far knee driven through under the body, foot lifted. */
const RUN_2: readonly string[] = [
  '...........................KKKKKKKK.........................',
  '.........................KKhGhhhhhhKK.......................',
  '........................KhhHHHHHHhGhhK......................',
  '.......................KhHHhHGHHHHHHhK......................',
  '.......................KGHHHHHhHHHHGHHK.....................',
  '......................KHhHHHHHGHHhHHHHLK....................',
  '......................KHHGHhHHHHHHHKKKSLK...................',
  '......................KHHHHHHHhGHHHHLLSdK...................',
  '......................KHhHGHHHHHHhLLLKKdK...................',
  '.......................KHHHhHLLLLLLLSKSdK...................',
  '.......................KHHHGHLLLLLSSSSSdK...................',
  '........................KHHHHhdSSSSSSSdK....................',
  '.........................KHhGhddSSSSdddK....................',
  '..........................KHHHhSSSSSdddK....................',
  '.........................KWWHGhhSSSSddWK....................',
  '.........................KWWWWLSSSddWWWvK...................',
  '........................KTTTWWLLddddWWTvK...................',
  '........................KTTTvvSdddWWTTTTvK..................',
  '.......................KTTTTvvddWWWWTTvvLLKK................',
  '.......................KTTTvvLdWWWTTTTvvLLLK................',
  '.......................KTTTvvLdWTTTTTTvvdddK................',
  '.......................KTTTTvWdTTTTTTTTvWddK................',
  '.......................KTTTTvWdTTTTTTTTTWWdK................',
  '.......................KTTTTTTWTTTTTTTTTvWdK................',
  '.......................KTTTTTTWTTTTTTTTTTvWK................',
  '.......................KTTTTTTTTTTTTTTTTTvWK................',
  '.......................KTTTTTTTTTTTTTTTTvvLK................',
  '.......................KTTTTTTTTTTTTTTTTvvLK................',
  '.......................KTTTTTTTTTTTTTTvvLLdK................',
  '.......................KTTTTTTTTTTTTTTvvKKKK................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KvTTTTTTTTTTTTvK.....................',
  '.......................KvvTTTTTTTTTTvvK.....................',
  '.......................KQvvTTTTTTTTvvvQK....................',
  '.......................KQQvvvvTTTvvvvQqK....................',
  '......................KPPQQvvvvvvvvQQQqK....................',
  '......................KPPPQQQQvvvQQQQPPqK...................',
  '......................KPPPPQQQQQQQQPPPPqQK..................',
  '......................KPPPPPPPQQQPPPPPqqdK..................',
  '.......................KPPPPPPPPPPPPPPqqdK..................',
  '.......................KqPPPPPPPPPPPPPqqDK..................',
  '........................KqqPPPPPPPPPPqqdDK..................',
  '.........................KKqPPPPPPPPPqqdDK..................',
  '...........................KPPPPPPPPPqqDK...................',
  '............................KPPPPPPPqqdDK...................',
  '............................KqqPPPqqqddK....................',
  '............................KqqqqqqqndDK....................',
  '............................KLLqqqLLnnK.....................',
  '............................KLLLLLLLNnnKK...................',
  '............................KSSLLLddNNNnnKK.................',
  '............................KSSSSSddNNNNNnK.................',
  '............................KSSSSSddNNNNNNNK................',
  '............................KSSddSdKNNNNNNNK................',
  '.............................KddddK.KKNNNNK.................',
  '.............................KdbbdK...KKKKK.................',
  '.............................KbbbbK.........................',
  '.............................KbBBbbK........................',
  '............................KBBBBBBbKK......................',
  '............................KBBBBBBBbbKK....................',
  '.............................KnBBBBBBBbbK...................',
  '.............................KKnnBBBBBBBbK..................',
  '...............................KKnBBBBBBBbK.................',
  '.................................KnnBBBBBnK.................',
  '..................................KKnnnnnnK.................',
  '....................................KKKKKK..................',
];

/** Full stride, arms at their widest — the airborne beat of the cycle. */
const RUN_3: readonly string[] = [
  '...........................KKKKKKKK.........................',
  '.........................KKhGhhhhhhKK.......................',
  '........................KhhHHHHHHhGhhK......................',
  '.......................KhHHhHGHHHHHHhK......................',
  '.......................KGHHHHHhHHHHGHHK.....................',
  '......................KHhHHHHHGHHhHHHHLK....................',
  '......................KHHGHhHHHHHHHKKKSLK...................',
  '......................KHHHHHHHhGHHHHLLSdK...................',
  '......................KHhHGHHHHHHhLLLKKdK...................',
  '.......................KHHHhHLLLLLLLSKSdK...................',
  '.......................KHHHGHLLLLLSSSSSdK...................',
  '........................KHHHHhdSSSSSSSdK....................',
  '.........................KHhGhddSSSSdddK....................',
  '..........................KHHHhSSSSSdddK....................',
  '.........................KWWHGhhSSSSddWK....................',
  '.........................KWWWWLSSSddWWWvK...................',
  '.....................KK.KTTTWWLLddddWWTvK...................',
  '....................KddKWTTTvvSdddWWTTTTvK..................',
  '....................KDDWTTTTvvddWWWWTTTTvK..................',
  '....................KDDWTTTvvLdWWWTTTTTTvK..................',
  '...................KDDDTTTTvvLdWTTTTTTTTvK..................',
  '...................KDDWTTTTTvWdTTTTTTTTTvK..................',
  '...................KDWWTTTTTvWdTTTTTTTTTTvK.................',
  '...................KDWTTTTTTTTWTTTTTTTTTTTWK................',
  '..................KDDvTTTTTTTTWTTTTTTTTTTTvK................',
  '..................KDDvvTTTTTTTTTTTTTTTTTTTvvK...............',
  '..................KDDdvTTTTTTTTTTTTTTTTTTTvvLK..............',
  '...................KDKKTTTTTTTTTTTTTTTTTTvvvSLK.............',
  '....................K..KTTTTTTTTTTTTTTTTvvvLSdK.............',
  '.......................KTTTTTTTTTTTTTTTvKKLLSSdK............',
  '.......................KTTTTTTTTTTTTTTvK..KSSSdK............',
  '.......................KTTTTTTTTTTTTTTvK...KSSdK............',
  '.......................KTTTTTTTTTTTTTTvK...KSSdK............',
  '.......................KTTTTTTTTTTTTTTvK...KSSdK............',
  '.......................KTTTTTTTTTTTTTvvK...KSSdK............',
  '.......................KTTTTTTTTTTTTTvvK...KSSdK............',
  '.......................KTTTTTTTTTTTTTvvK....KSSdK...........',
  '.......................KTTTTTTTTTTTTTvvK....KSSdK...........',
  '.......................KvTTTTTTTTTTTTvK.....KddK............',
  '.......................KvvTTTTTTTTTTvvK......KK.............',
  '.......................KQvvTTTTTTTTvvvQK....................',
  '......................KPQQvvvvTTTvvvvQPQK...................',
  '.....................KQPPQQvvvvvvvvQQQPPQKK.................',
  '....................KQPPPPQQQQvvvQQQQPPPPQK.................',
  '...................KQPPPPPPQQQQQQQQPPPPPPPqK................',
  '...................KPPPPPPPPPPQQQPPPPPPPPPqK................',
  '...................KPPPPPPPPPPPPPPPPPPPPPPqqKK..............',
  '.................KKPPPPPPPPPPPPPPPPPPPPPPPqqLLK.............',
  '................KddqPPPPPPPPPPPPPPPPPPPPPPqqSSLK............',
  '...............KdDDqPPPPPPPPPqqqqqPPPPPPPPqqSSdK............',
  '..............KdDDDdqqPPPPPqqKKKKKqqqPPPqqqLSSSdK...........',
  '.............KdDDDDdqqqqqqqKK.....KKKqqqqqLLSSSdK...........',
  '............KdDDDDDDddKKKKK..........KKKKKLSSSSdK...........',
  '...........KdDDDDDDDdK....................KSSSSSdK..........',
  '..........KdDDDDDDDKK.....................KSSSSSdK..........',
  '.........KdDDDDDDDK........................KSSSSSdK.........',
  '.......KKnnnDDDDDK.........................KdSSSddK.........',
  '.....KKnnnnnnDDKK...........................KSSddddK........',
  '...KKnnNNNNNnDK..............................KddbbbK........',
  '.KKnnNNNNNNNNK...............................KdbbbbbKK......',
  'KnnNNNNNNNNNK.................................KbBBBBbbK.....',
  'KNNNNNNNNNKK..................................KBBBBBBBbKK...',
  'KNNNNNNNKK.....................................KBBBBBBBbbK..',
  'KNNNNNKK.......................................KnnBBBBBBBbKK',
  '.KKKKK..........................................KKnBBBBBBBbK',
  '..................................................KnnBBBBBnK',
  '...................................................KKnBBBBnK',
  '.....................................................KnnnnnK',
  '......................................................KKKKK.',
  '............................................................',
  '............................................................',
  '............................................................',
];

/** Passing, opposite phase: heel kicked up behind. */
const RUN_4: readonly string[] = [
  '...........................KKKKKKKK.........................',
  '.........................KKhGhhhhhhKK.......................',
  '........................KhhHHHHHHhGhhK......................',
  '.......................KhHHhHGHHHHHHhK......................',
  '.......................KGHHHHHhHHHHGHHK.....................',
  '......................KHhHHHHHGHHhHHHHLK....................',
  '......................KHHGHhHHHHHHHKKKSLK...................',
  '......................KHHHHHHHhGHHHHLLSdK...................',
  '......................KHhHGHHHHHHhLLLKKdK...................',
  '.......................KHHHhHLLLLLLLSKSdK...................',
  '.......................KHHHGHLLLLLSSSSSdK...................',
  '........................KHHHHhdSSSSSSSdK....................',
  '.........................KHhGhddSSSSdddK....................',
  '..........................KHHHhSSSSSdddK....................',
  '.........................KWWHGhhSSSSddWK....................',
  '.........................KWWWWLSSSddWWWvK...................',
  '........................KTTTWWLLddddWWTvK...................',
  '........................KTTTvvSdddWWTTTTvK..................',
  '.......................KTTTTvvddWWWWTTTTvK..................',
  '.......................KTTTvvLdWWWTTTTTTvK..................',
  '.......................KTTTvvLdWTTTTTTTTvK..................',
  '.......................KTTTTvWdTTTTTTTTTvK..................',
  '.......................KTTTTvWdTTTTTTTTTvK..................',
  '.......................KTTTTTTWTTTTTTTTTTvK.................',
  '.......................KTTTTTTWTTTTTTTTTTvK.................',
  '.......................KTTTTTTTTTTTTTTTTTvvK................',
  '......................KTTTTTTTTTTTTTTTTTTvvLK...............',
  '......................KTTTTTTTTTTTTTTTTTvvvdK...............',
  '......................KTTTTTTTTTTTTTTTTTvvLSdK..............',
  '.......................KTTTTTTTTTTTTTTvvKLLSdK..............',
  '.......................KTTTTTTTTTTTTTTvK.KSSdK..............',
  '.......................KTTTTTTTTTTTTTTvK.KSSdK..............',
  '.......................KTTTTTTTTTTTTTTvK.KSSdK..............',
  '.......................KTTTTTTTTTTTTTTvK.KSSdK..............',
  '.......................KTTTTTTTTTTTTTvvK.KSSdK..............',
  '.......................KTTTTTTTTTTTTTvvK.KSSdK..............',
  '.......................KTTTTTTTTTTTTTvvK.KSSdK..............',
  '.......................KTTTTTTTTTTTTTvvK.KSSdK..............',
  '.......................KvTTTTTTTTTTTTvK..KddK...............',
  '.......................KvvTTTTTTTTTTvvK...KK................',
  '.......................KQvvTTTTTTTTvvvQK....................',
  '.......................KQQvvvvTTTvvvvQqK....................',
  '.......................KPQQvvvvvvvvQQQqK....................',
  '......................KPPPQQQQvvvQQQQPPqK...................',
  '......................KPPPPQQQQQQQQPPPPqK...................',
  '......................KPPPPPPPQQQPPPPPqK....................',
  '......................KPPPPPPPPPPPPPPPqK....................',
  '.....................KqPPPPPPPPPPPPPPPqK....................',
  '.....................KqqPPPPPPPPPPPPPPqK....................',
  '....................KDdqqqPPPPPPPPPPPqK.....................',
  '...................KdDddqqqqqPPPPPPPPqK.....................',
  '..................KnnnDdddKKKqPPPPPPPqK.....................',
  '...............KKKnnnnnDdK...KqqPPPqqK......................',
  '............KKKnnnNNNNnDK.....KqqqqqK.......................',
  '...........KnnnNNNNNNNNK......KLqqqLK.......................',
  '..........KnNNNNNNNNNNK.......KLLLLLK.......................',
  '..........KNNNNNNNNNNNK.......KSLLLdK.......................',
  '..........KNNNNNNNNKKK........KSSSSdK.......................',
  '..........KNNNNNKKK...........KSSSSdK.......................',
  '...........KKKKK..............KSSdSdK.......................',
  '..............................KdddddK.......................',
  '..............................KddbddK.......................',
  '..............................KbbbbbK.......................',
  '..............................KbbBbbbK......................',
  '..............................KBBBBBbbKK....................',
  '..............................KBBBBBBBbbK...................',
  '..............................KnBBBBBBBBbKK.................',
  '...............................KnnBBBBBBBbbK................',
  '................................KKnnBBBBBBnK................',
  '..................................KKnBBBBBBnK...............',
  '....................................KnnnnnnK................',
  '.....................................KKKKKKK................',
];

/** Arms thrown up and out, knees tucked. */
const JUMP: readonly string[] = [
  '...........................KKKKKKKK.........................',
  '.........................KKhGhhhhhhKK.......................',
  '........................KhhHHHHHHhGhhK......................',
  '.......................KhHHhHGHHHHHHhK......................',
  '.......................KGHHHHHhHHHHGHHK.....................',
  '......................KHhHHHHHGHHhHHHHLK....................',
  '......................KHHGHhHHHHHHHKKKSLK...................',
  '......................KHHHHHHHhGHHHHLLSdK...................',
  '......................KHhHGHHHHHHhLLLKKdK...................',
  '.......................KHHHhHLLLLLLLSKSdK...................',
  '.......................KHHHGHLLLLLSSSSSdK...................',
  '........................KHHHHhdSSSSSSSdK....................',
  '.........................KHhGhddSSSSdddK....................',
  '..........................KHHHhSSSSSdddK....................',
  '.........................KWWHGhhSSSSddWK....................',
  '.........................KWWWWLSSSddWWWvK...................',
  '.............KK.........KTTTWWLLddddWWTvK........KKK........',
  '............KddK........KTTTvvSdddWWTTTTvK......KLLLK.......',
  '............KDDdK......KTTTTvvddWWWWTTTTvK.....KLSSdK.......',
  '............KDDDdK.....KTTTvvLdWWWTTTTTTvK....KLSSSdK.......',
  '.............KDDDdK...KTTTTvvLdWTTTTTTTTTvK..KLSSSdK........',
  '..............KDDDdKKKWTTTTTvWdTTTTTTTTTTTWKKLSSSdK.........',
  '...............KDDDddWTTTTTTvWdTTTTTTTTTTTvWLSSSdK..........',
  '................KDDDDTTTTTTTTTWTTTTTTTTTTTvvSSSdK...........',
  '.................KDDDvTTTTTTTTWTTTTTTTTTTTvvSSdK............',
  '.................KDDDvvTTTTTTTTTTTTTTTTTTvvvdddK............',
  '..................KKKKKTTTTTTTTTTTTTTTTTTKKKKKK.............',
  '.......................KTTTTTTTTTTTTTTTvK...................',
  '.......................KTTTTTTTTTTTTTTTvK...................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KvTTTTTTTTTTTTvK.....................',
  '.......................KvvTTTTTTTTTTvvK.....................',
  '.......................KQvvTTTTTTTTvvvQK....................',
  '.......................KQQvvvvTTTvvvvQPQK...................',
  '......................KPPQQvvvvvvvvQQQPPQK..................',
  '......................KPPPQQQQvvvQQQQPPPPQK.................',
  '.....................KPPPPPQQQQQQQQPPPPPPqK.................',
  '.....................KPPPPPPPPQQQPPPPPPPPqK.................',
  '.....................KPPPPPPPPPPPPPPPPPPPPqK................',
  '....................KPPPPPPPPPPPPPPPPPPPPqqLK...............',
  '....................KqPPPPPPPPPPPPPPPPPPPqqLLK..............',
  '...................KDqqPPPPPPqqqqqPPPPPPPqqSdK..............',
  '...................KDdqqqqqqqKKKKKqqPPPqqqLSdK..............',
  '...................KDddqqqKKK.....KKqqqqqLLSSdK.............',
  '...................KDDdddK..........KKKLLLSSSdK.............',
  '..................KDDDDddK.............KLSSSSdK.............',
  '..................KDDDDDK...............KSddddK.............',
  '..................KDDDDDK...............KdddddK.............',
  '.................KnnnnDK................KdbbbbK.............',
  '...............KKnnnnnnK................KbbbbbK.............',
  '.............KKnnNNNNNK.................KbBBBBbKK...........',
  '............KnnNNNNNNNK.................KBBBBBBbbKK.........',
  '...........KnNNNNNNNNNK.................KnBBBBBBBbbK........',
  '...........KNNNNNNNNNK...................KnBBBBBBBBbKK......',
  '...........KNNNNNNNKK.....................KnnBBBBBBBbbK.....',
  '...........KNNNNNKK........................KKnnBBBBBBnK.....',
  '............KKKKK............................KKnBBBBBnK.....',
  '...............................................KnnBBBnK.....',
  '................................................KKnnnK......',
  '..................................................KKK.......',
  '............................................................',
  '............................................................',
  '............................................................',
  '............................................................',
];

/** Arms wide, legs splayed and trailing. */
const FALL: readonly string[] = [
  '...........................KKKKKKKK.........................',
  '.........................KKhGhhhhhhKK.......................',
  '........................KhhHHHHHHhGhhK......................',
  '.......................KhHHhHGHHHHHHhK......................',
  '.......................KGHHHHHhHHHHGHHK.....................',
  '......................KHhHHHHHGHHhHHHHLK....................',
  '......................KHHGHhHHHHHHHKKKSLK...................',
  '......................KHHHHHHHhGHHHHLLSdK...................',
  '......................KHhHGHHHHHHhLLLKKdK...................',
  '.......................KHHHhHLLLLLLLSKSdK...................',
  '.......................KHHHGHLLLLLSSSSSdK...................',
  '........................KHHHHhdSSSSSSSdK....................',
  '.........................KHhGhddSSSSdddK....................',
  '..........................KHHHhSSSSSdddK....................',
  '.........................KWWHGhhSSSSddWK....................',
  '.........................KWWWWLSSSddWWWvK...................',
  '........................KTTTWWLLddddWWTvK...................',
  '........................KTTTvvSdddWWTTTTvK..................',
  '.......................KTTTTvvddWWWWTTTTvK..................',
  '.......................KTTTvvLdWWWTTTTTTvK..................',
  '......................KTTTTvvLdWTTTTTTTTvK..................',
  '.......KKKKK.........KWTTTTTvWdTTTTTTTTTTTKK........KKKKK...',
  '.......KddddKKK.....KWTTTTTTvWdTTTTTTTTTTTWK....KKKKLLLLLK..',
  '.......KDDDDdddKKKKKWTTTTTTTTTWTTTTTTTTTTTvvKKKKLLLLSSSddK..',
  '.......KKDDDDDDdddddvTTTTTTTTTWTTTTTTTTTTTTvWLLLSSSSdddKK...',
  '.........KKKDDDDDDDDvvTTTTTTTTTTTTTTTTTTTTvvSSSSSdddKKK.....',
  '............KKKDDDDDdvvTTTTTTTTTTTTTTTTTTvvvLSSddKKK........',
  '...............KKKDKKKKTTTTTTTTTTTTTTTTTvKKKdddKK...........',
  '..................K....KTTTTTTTTTTTTTTTvK...KKK.............',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTTvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KTTTTTTTTTTTTTvvK....................',
  '.......................KvTTTTTTTTTTTTvK.....................',
  '.......................KvvTTTTTTTTTTvvK.....................',
  '.......................KQvvTTTTTTTTvvvQK....................',
  '.......................KQQvvvvTTTvvvvQqK....................',
  '......................KPPQQvvvvvvvvQQQPqK...................',
  '......................KPPPQQQQvvvQQQQPPqK...................',
  '.....................KPPPPPQQQQQQQQPPPPPqK..................',
  '.....................KPPPPPPPPQQQPPPPPPPPQK.................',
  '....................KPPPPPPPPPPPPPPPPPPPPqK.................',
  '....................KPPPPPPPPPPPPPPPPPPPPqK.................',
  '....................KPPPPPPPPPPPPPPPPPPPPPqK................',
  '....................KPPPPPPPPPPqPPPPPPPPPqqK................',
  '....................KPPPPPPPPPqKqPPPPPPPPqqK................',
  '...................KdqqPPPPPPqK.KqPPPPPPPqqdK...............',
  '..................KddqqqqqqqqK...KqqPPPqqqLSLK..............',
  '..................KDDddqqqKKK.....KKqqqqqLLSdK..............',
  '.................KDDDddddK..........KKqLLLSSSdK.............',
  '.................KDDDDDddK............KLLSSSSdK.............',
  '................KDDDDDDDK..............KSSSSSSdK............',
  '................KDDDDDDK................KSSSSSdK............',
  '...............KDDDDDDK.................KdSSSSSdK...........',
  '...............KDDDDDDK..................KSSSSSdK...........',
  '..............KDDDDDDK....................KSSSdddK..........',
  '..............KDDDDDK.....................KdSdddbK..........',
  '.............KnnnnDDK......................KddbbbbK.........',
  '............KnnnnnnK........................KbbbBbbKK.......',
  '...........KnNNNNNK.........................KbBBBBBbbK......',
  '.........KKnNNNNNNK..........................KBBBBBBBbKK....',
  '........KnnNNNNNNNK..........................KnBBBBBBBbbK...',
  '.......KnNNNNNNNKK............................KnnBBBBBBBbK..',
  '......KnNNNNNNNK...............................KKnBBBBBBBbK.',
  '......KNNNNNNNK..................................KnnBBBBBnK.',
  '......KNNNNNKK....................................KKnnnnnnK.',
  '.......KKKKK........................................KKKKKK..',
];

/** Leaning back, legs thrown forward. Invented — the reference has no slide. */
const SLIDE: readonly string[] = [
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '..........KKKKKKKK......................................................',
  '........KKhhhhhhhhK.....................................................',
  '.......KhhHHHHGHHHhK....................................................',
  '......KhHGHHhHHHHHHhK...................................................',
  '......KHHHHHHHHGHHHHhK..................................................',
  '......KHHhGHHHHHHHhHLLK.................................................',
  '.....KHHHHHHhHHHGHKKKdK.................................................',
  '.....KhHHHHGHHHhHHLLSdK.................................................',
  '......KHHhHHLLLLLLLSKddKKKK.............................................',
  '......KHHHHHLLLLLLSSKddWWWWKK...........................................',
  '......KGHHHHddSSSSSSSddvTTTWWKK.........................................',
  '.......KHhHHhddSSSSSSddvvTTTTWWKK.......................................',
  '........KKHHhhdddSSSSSdLvvvTTTTWWKK.....................................',
  '..........KKKKGdddSSSSSLLvvTTTTTTWWKK...................................',
  '..............KWWdSSSSSSLLLTTTTTTTTWWKK.................................',
  '..............KWWWdSSSSSSLLTTTTTTTTTTWWKK...............................',
  '..............KTvWddSSSSddWTTTTTTTTTTTTWWKKKKKKK........................',
  '..............KTTvWddSSSddWTTTTTTTTTTvvLLLLLLLLK........................',
  '..............KTTTWWddSSddTTTTTTTTTTTvvLLLLSSSdK........................',
  '..............KTTTTWWdddddTTTTTTTTTTTvvSSSSdddddKK......................',
  '..............KTTTTTWWddddTTTTTTTTTTTvvddddddddQQQKK....................',
  '...............KTTTTTWWWWWTTTTTTTTTTTvvddddWWWWQPPQQKK..................',
  '...............KvTTTTTWWWWTTTTTTTTTTTTTWWWWWWWWPPPPPQQK.................',
  '...............KvvTTTTTTTTTTTTTTTTTTTTTWWWWTTvvPPPPPPPQK................',
  '...............KdvvvTTTTTTTTTTTTTTTTTTTTTTTTTvvPPPPPPPPQKKK.............',
  '...............KddvKvvvvTTTTTTTTTTTTTTTTTTTTTvvPPPPPPPPqQLLKK...........',
  '...............KKKK.KKKKvvvvTTTTTTTTTTTTTTTTTvvPPPPPPPPqqSSLLKKK........',
  '........................KKKKvvvTTTTTTTTTTTTTvvQPPPPPPPPqqSSSSLLLKKK.....',
  '............................KKKvvvvTTTTTTTTvvvQPPPPPPPPqqSSSSSddbbbKKKKK',
  '...............................KKKKvvvvvvvvvvQPPPPPPPPPqqSSSSddbbbBbbbbK',
  '...................................KKKKvvvvQQQPPPPPPPPqqLdSSSddbBBBBBBnK',
  '.......................................KKKQQQqPPPPPPPqqqLddddddnBBBBBBnK',
  '..........................................KKKKqqqqqqqqqddddddddnnnBBBBnK',
  '..............................................KKKKKKKdddddddddnLnnnnnnnK',
  '.....................................................KKKKDddddnnnnnnnnnK',
  '.........................................................KKKKDNnnnnnnnnK',
  '.............................................................KKKKNnnnnnK',
  '.................................................................KKKKKK.',
];

/** Face-down and horizontal, after the prone reference. Sized to the collision
 * box exactly, so the platform edges are never ambiguous. */
const CORPSE: readonly string[] = [
  '............................................................',
  '................KKKKKKKKKKK.................................',
  '...............KWWWWWWWWWWWKKKKKKK..........................',
  '..............KWTTTTTTTTTTTWWWWWWWKKKK......................',
  '........KKKKKKWvTvvvTTTTTTTTTTTTTTWWWWKKKK..................',
  '.......KGhhhhhhvvvvvvvvTTTTTTTTTTTTTTTWWQQKKKK..............',
  '......KhHhHHHHGhvLLLvvvvvTTTTTTTTTTTTTTvWqQQQQKK............',
  '.....KhHHGLLLLLLhLLLLLLvvvTTTTTTTTTTTTTvWqPPPPQQKK..........',
  '.....KhHHHLLLLLLLSSSLLLLLvTTTTTTTTTTTTTTvWPPPPPqQLKKKK......',
  '.....KHHHLSSSSSSLSSSSSSLLLTTTTTTTTTTTTTTvWPPPPPPqQbbbbKKKK..',
  '.....KHHHLSSSSKKSSSSSSSSdLTTTTTTTTTTTTTTvvPPPPPPqQBBBBbbbbKK',
  '.....KhHHdSSSSSSSSSSSSSSddTTTTTTTTTTTTTvvQPPPPPPqqBBBBBBBBbK',
  '...KKLGHHdSSSSSSSSSdddddddTTTTTTTTTTTTTvvQPPPPPPqqBBBBBBBBnK',
  '...KLLLHHhSddddddddddddddWTTTTTTTTTTTTvvQPPPPPPqqbnBBBBBBBnK',
  '...KddLLHhdddddddddKWWWWWWvvvvvvvvvvvvvvQPPPPPqqqbnnnnnnnBnK',
  '...KKKKKKLdddddddKK.KKKKKKKKKKKKKKKKKvQQqqqqqqKqdnnnnnnnnnnK',
  '.........KddddKKK....................KKKKKKKKK.KKKKKnnnnnnnK',
  '.........KKKKK......................................KKKnnnK.',
  '.......................................................KKK..',
  '............................................................',
];

/**
 * Sprites are drawn larger than their hitbox and anchored feet-to-feet, so hair
 * and swinging limbs overhang. That reads as generous rather than unfair — you
 * clip scenery with your hair without dying for it.
 */
const STAND_OFFSET = { ox: -px(4), oy: -px(4) };
const SLIDE_OFFSET = { ox: -px(6), oy: -px(4) };

export const SPRITES = {
  run1: { rows: RUN_1, ...STAND_OFFSET },
  run2: { rows: RUN_2, ...STAND_OFFSET },
  run3: { rows: RUN_3, ...STAND_OFFSET },
  run4: { rows: RUN_4, ...STAND_OFFSET },
  jump: { rows: JUMP, ...STAND_OFFSET },
  fall: { rows: FALL, ...STAND_OFFSET },
  slide: { rows: SLIDE, ...SLIDE_OFFSET },
  corpse: { rows: CORPSE, ox: 0, oy: 0 },
} satisfies Record<string, Sprite>;

export type SpriteName = keyof typeof SPRITES;

export const RUN_CYCLE: readonly SpriteName[] = ['run1', 'run2', 'run3', 'run4'];

/** The collision box is sized to match the corpse sprite exactly. */
export const CORPSE_SPRITE_H = CORPSE.length;
export const CORPSE_SPRITE_W = CORPSE[0]!.length;

/**
 * Baked once into offscreen canvases — per-pixel fillRect for a dozen ghosts
 * and sixty corpses every frame is exactly the cost a phone can't absorb.
 */
export class SpriteBank {
  private baked = new Map<SpriteName, HTMLCanvasElement>();

  constructor() {
    for (const name of Object.keys(SPRITES) as SpriteName[]) {
      this.baked.set(name, bake(SPRITES[name].rows));
    }
  }

  get(name: SpriteName): HTMLCanvasElement {
    return this.baked.get(name)!;
  }

  /** Draw with the sprite's offset applied to a hitbox-space position. */
  draw(ctx: CanvasRenderingContext2D, name: SpriteName, hitboxX: number, hitboxY: number): void {
    const s = SPRITES[name];
    ctx.drawImage(this.get(name), Math.round(hitboxX + s.ox), Math.round(hitboxY + s.oy));
  }
}

function bake(rows: readonly string[]): HTMLCanvasElement {
  const h = rows.length;
  const w = rows[0]?.length ?? 0;
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d')!;
  for (let y = 0; y < h; y++) {
    const row = rows[y]!;
    for (let x = 0; x < row.length; x++) {
      const color = SPRITE_PALETTE[row[x]!];
      if (color === undefined) continue;
      ctx.fillStyle = color;
      ctx.fillRect(x, y, 1, 1);
    }
  }
  return canvas;
}

/** Rows must be rectangular and use only known palette letters. */
export function validateSprites(): string[] {
  const problems: string[] = [];
  for (const [name, sprite] of Object.entries(SPRITES)) {
    const width = sprite.rows[0]?.length ?? 0;
    sprite.rows.forEach((row, y) => {
      if (row.length !== width) {
        problems.push(`${name} row ${y}: ${row.length} chars, expected ${width}`);
      }
      for (const ch of row) {
        if (ch !== '.' && SPRITE_PALETTE[ch] === undefined) {
          problems.push(`${name} row ${y}: unknown palette char "${ch}"`);
        }
      }
    });
  }
  return problems;
}
